/**
 Generated by Multiple Back-Propagation Version 2.2.2
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 3 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void QoE_Estimator(double * inputs, double * outputs) {
	double mainWeights[] = {-0.788223989025525, -0.094474566726867, 1.496739847656628, 1.763686040718159, -1.903030984102726, 0.642334326063278, -1.151808104642765, 0.195778993761345, -2.438147799676302, -0.593447767630059, 0.602159330161696, 1.841888272109078, -1.668291515410757, 1.132531695902347, 1.770256249167634, -1.543624462297342, -0.300179501200067, 0.218045746602884, 0.549917901597161, -0.420158477741495, 0.165459965494116, 0.626640712066218, -0.317482940512069, -0.165924553270408, -3.316089679297547, 0.901781718110168, -2.227550874229060, -0.468212813041442, -0.254505118375575, 1.753316060915204, -0.471577244624611, 0.276860328465251, -8.533724138983054, -7.815997751844567, 0.062513227206194, -0.028703413820191, -0.355241766960234, -1.014473189203496, 0.239401342551138, -0.891442488512514, 0.040038287080412, 1.014695308785556, 1.716301939415027, -1.836208299980111, -2.218906644053716, -0.002026100423785, 0.325609116530568, 2.762985101033591, 1.081971585914914, -6.798320012264649, -0.435605988610366};
	double * mw = mainWeights;
	double hiddenLayer1outputs[10];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 128.000000000000000) / 1436.000000000000000;
	inputs[1] = -1.0 + (inputs[1] - 0.000000000000000) / 10.000000000000000;
	inputs[2] = -1.0 + (inputs[2] - 0.000000000000000) / 5.000000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[0]));
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[1]));
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[2]));
	hiddenLayer1outputs[3] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[3] += *mw++ * inputs[c];
	hiddenLayer1outputs[3] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[3]));
	hiddenLayer1outputs[4] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[4] += *mw++ * inputs[c];
	hiddenLayer1outputs[4] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[4]));
	hiddenLayer1outputs[5] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[5] += *mw++ * inputs[c];
	hiddenLayer1outputs[5] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[5]));
	hiddenLayer1outputs[6] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[6] += *mw++ * inputs[c];
	hiddenLayer1outputs[6] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[6]));
	hiddenLayer1outputs[7] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[7] += *mw++ * inputs[c];
	hiddenLayer1outputs[7] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[7]));
	hiddenLayer1outputs[8] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[8] += *mw++ * inputs[c];
	hiddenLayer1outputs[8] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[8]));
	hiddenLayer1outputs[9] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[9] += *mw++ * inputs[c];
	hiddenLayer1outputs[9] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[9]));
	outputs[0] = *mw++;
	for(c = 0; c < 10; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = 1.0 / (1.0 + exp(-outputs[0]));
	outputs[0] = 28.546600000000002 + (outputs[0] - 0.000000) * 16.112199999999998;
}
